"""
services/diffusion.py
Generative image integration using the Stability AI REST API.
Implements the two required generation features:
  1. Text-to-Image Generation
  2. Image Variation (implemented via image-to-image / strength-based remix,
     since Stability's v2 API does not have an OpenAI-style "variations"
     endpoint - this is the standard equivalent)

Per the project spec, generated bytes are returned to the caller (the
background worker), which is responsible for re-uploading them to our own
S3/R2 bucket. This module never trusts a provider-hosted URL.
"""
import os
import httpx

STABILITY_API_KEY = os.getenv("STABILITY_API_KEY")
STABILITY_HOST = "https://api.stability.ai"

HTTP_TIMEOUT_SECONDS = 60.0


class ContentPolicyError(Exception):
    """Raised when the provider rejects a prompt for safety/policy reasons."""
    pass


class GenerationError(Exception):
    """Raised for any other non-recoverable generation failure."""
    pass


def _check_response_for_known_errors(response: httpx.Response) -> None:
    if response.status_code == 403:
        # Stability returns 403 with a content_moderation reason for flagged prompts.
        raise ContentPolicyError(
            "Your prompt was rejected by the AI safety filter. Please try a different prompt."
        )
    if response.status_code == 429:
        raise GenerationError("Rate limit exceeded on the image generation provider.")
    if response.status_code >= 400:
        raise GenerationError(f"Generation provider error: {response.status_code} {response.text[:200]}")


async def generate_text_to_image(prompt: str) -> bytes:
    """
    Calls Stability AI's Stable Image Core (text-to-image) endpoint.
    Returns raw PNG image bytes.
    """
    url = f"{STABILITY_HOST}/v2beta/stable-image/generate/core"

    async with httpx.AsyncClient(timeout=HTTP_TIMEOUT_SECONDS) as http_client:
        response = await http_client.post(
            url,
            headers={
                "Authorization": f"Bearer {STABILITY_API_KEY}",
                "Accept": "image/*",
            },
            files={"none": ""},  # Stability requires multipart even with no file
            data={
                "prompt": prompt,
                "output_format": "png",
            },
        )
        _check_response_for_known_errors(response)
        return response.content


async def generate_image_variation(image_bytes: bytes, prompt: str, strength: float = 0.65) -> bytes:
    """
    Calls Stability AI's image-to-image endpoint to produce a stylistic
    variation of an existing image, guided by a text prompt.
    `strength` controls how much the output is allowed to diverge from the
    source image (0 = identical, 1 = ignores source almost entirely).
    """
    url = f"{STABILITY_HOST}/v2beta/stable-image/generate/core"

    async with httpx.AsyncClient(timeout=HTTP_TIMEOUT_SECONDS) as http_client:
        response = await http_client.post(
            url,
            headers={
                "Authorization": f"Bearer {STABILITY_API_KEY}",
                "Accept": "image/*",
            },
            files={"image": ("source.png", image_bytes, "image/png")},
            data={
                "prompt": prompt or "A creative stylistic variation of this image",
                "mode": "image-to-image",
                "strength": str(strength),
                "output_format": "png",
            },
        )
        _check_response_for_known_errors(response)
        return response.content
